---
- hosts: single
  become: yes
  become_user: wasadm
  tasks:
  - name: start all
    appserver_control:
      state: started
      psall: "{{psall}}"
    register: appserver_control
  - debug: var=appserver_control.stdout_lines
