---
- hosts: single
  become: yes
  become_user: wasadm
  tasks:
  - name: stop all
    appserver:
      state: stopped
      psall: "{{psall}}"
    register: appserver
  - debug: var=appserver.stdout_lines
